/**
 * ============================================================================
 * Lumina AI Legacy Block & Fallback Markdown Parser
 * ============================================================================
 * 
 * Parses markdown code blocks and XML tags generated by non-tool-calling models
 * or fallback streaming modes, translating them into actual workspace mutations:
 * 
 * 1. Fenced Code Blocks:
 *    - ` ```lumina-create <title>` -> saves new note to workspaceStore
 *    - ` ```lumina-update <title>` -> updates existing note
 *    - ` ```lumina-delete <title>` -> deletes target note
 * 
 * 2. Fallback Pseudo-Tags:
 *    - `<createFile title="..." folder="...">...</createFile>`
 *    - `<createFolder path="...">`
 *    - `<luminaQueryIndex>...</luminaQueryIndex>`
 *    - `<diagnoseSystem>...</diagnoseSystem>`
 *    - `<auditWikilinks>...</auditWikilinks>`
 * 
 * 3. Display Sanitization:
 *    - Strips applied action blocks from visible chat markdown so the conversation
 *      remains conversational and clean.
 */

import { cleanRawToolLeaks, extractParamsFromBody } from './toolCallInterceptor'

export const applyLegacyMarkdownBlocks = async (
  fullContent: string,
  workspaceStore: any,
  onWorkspaceChange?: (toolName: string, args: Record<string, any>, result: any) => void
): Promise<string> => {
  const normalizeWorkspaceFolder = (value?: string): string => {
    const folder = (value || '').trim().replace(/\\/g, '/').replace(/^\/+|\/+$/g, '')
    return /^(?:root|workspace root|vault root|project root|workspace|vault|\.)$/i.test(folder) ? '' : folder
  }
  const contentOutsideThink = (fullContent || '')
    .replace(/<think>[\s\S]*?<\/think>/gi, '')
    .replace(/<think>[\s\S]*$/gi, '')
  const allNotes = workspaceStore.notes || []
  let appliedCreations = 0
  let appliedFolders = 0
  let appliedUpdates = 0
  let appliedDeletions = 0

  const parseLuminaBlocks = (text: string, prefix: string) => {
    const blocks: Array<{ title: string; content: string }> = []
    const searchStart = '```' + prefix + ' '
    let i = 0
    while (i < text.length) {
      const blockStart = text.indexOf(searchStart, i)
      if (blockStart === -1) break

      const titleAfter = blockStart + searchStart.length
      const titleEnd = text.indexOf('\n', titleAfter)
      if (titleEnd === -1) break
      const title = text.slice(titleAfter, titleEnd).trim()

      let depth = 1
      let fenceDepth = 0
      let pos = titleEnd + 1

      while (pos < text.length && depth > 0) {
        const bt = text.indexOf('```', pos)
        if (bt === -1) break

        const afterBt = text.slice(bt + 3)
        const trimmed = afterBt.trimStart()

        if (
          trimmed.startsWith('lumina-create ') ||
          trimmed.startsWith('lumina-update ') ||
          trimmed.startsWith('lumina-delete ')
        ) {
          depth++
        } else if (afterBt.length > 0 && !/^\s/.test(afterBt[0])) {
          fenceDepth++
        } else if (fenceDepth > 0) {
          fenceDepth--
        } else {
          depth--
        }

        pos = bt + 3
      }

      const content = text.slice(titleEnd + 1, pos - 3).replace(/\n$/, '')
      blocks.push({ title, content })
      i = pos
    }
    return blocks
  }

  // 1. Process lumina-create
  const createMatches = parseLuminaBlocks(contentOutsideThink, 'lumina-create')
  for (const { title, content } of createMatches) {
    const newNote = {
      id: crypto.randomUUID(),
      title,
      code: content,
      language: 'markdown',
      tags: '',
      timestamp: Date.now()
    }
    await workspaceStore.saveNote(newNote)
    appliedCreations++
    onWorkspaceChange?.('createFile', { title, content }, { success: true, ...newNote, writtenContent: content })
  }

  // 1b. Fallback XML pseudo tags: <createFile title="..." ...>content</createFile>
  const xmlCreateMatches = [
    ...contentOutsideThink.matchAll(
      /<create(?:File|_file)\s+title=["']([^"']+)["'](?:\s+folder=["']([^"']*)["'])?[^>]*>([\s\S]*?)<\/create(?:File|_file)>/gi
    )
  ]
  for (const match of xmlCreateMatches) {
    const title = match[1].trim()
    const folderId = normalizeWorkspaceFolder(match[2])
    const content = match[3].trim()

    if (title && !createMatches.some((c) => c.title === title)) {
      if (folderId && (window as any).api?.createFolder) {
        try {
          await (window as any).api.createFolder(folderId)
        } catch (_) {}
      }
      const newNote = {
        id: crypto.randomUUID(),
        title,
        code: content,
        folderId: folderId || '',
        language: 'markdown',
        tags: '',
        timestamp: Date.now()
      }
      await workspaceStore.saveNote(newNote)
      appliedCreations++
      onWorkspaceChange?.('createFile', { title, folder: folderId, content }, { success: true, ...newNote, writtenContent: content })
    }
  }

  // 1c. Process <createFolder path="..."> pseudo tags
  const xmlFolderMatches = [
    ...contentOutsideThink.matchAll(/<create(?:Folder|_folder)\s+path=["']([^"']+)["'][^>]*>/gi)
  ]
  for (const match of xmlFolderMatches) {
    const folderPath = normalizeWorkspaceFolder(match[1])
    if (folderPath && (window as any).api?.createFolder) {
      try {
        await (window as any).api.createFolder(folderPath)
        appliedFolders++
        onWorkspaceChange?.('createFolder', { path: folderPath }, { success: true, path: folderPath })
      } catch (_) {}
    }
  }

  // 2. Process lumina-update
  const updateMatches = parseLuminaBlocks(contentOutsideThink, 'lumina-update')
  for (const { title, content } of updateMatches) {
    const cleanTitle = title.toLowerCase().replace(/\.md$/, '')
    const targetNote = allNotes.find((n: any) => {
      const nTitle = (n.title || '').toLowerCase().replace(/\.md$/, '')
      return nTitle === cleanTitle
    })

    if (targetNote) {
      const updatedNote = { ...targetNote, code: content, timestamp: Date.now() }
      await workspaceStore.saveNote(updatedNote)
      if (workspaceStore.selectedNote?.id === targetNote.id) {
        workspaceStore.setSelectedNote(updatedNote)
      }
      appliedUpdates++
    }
  }

  // 3. Process lumina-delete
  const deleteMatches = [...contentOutsideThink.matchAll(/```lumina-delete\s+([^\n]+?)\s*```/g)]
  for (const match of deleteMatches) {
    const title = match[1].trim()
    const cleanTitle = title.toLowerCase().replace(/\.md$/, '')
    const targetNote = allNotes.find((n: any) => {
      const nTitle = (n.title || '').toLowerCase().replace(/\.md$/, '')
      return nTitle === cleanTitle
    })

    if (targetNote) {
      try {
        const deleteFn = workspaceStore.deleteNote || workspaceStore.deleteSnippet
        await deleteFn.call(workspaceStore, targetNote.id, true)
        appliedDeletions++
      } catch (e) {
        console.warn(`[StreamRunner] Failed to delete "${title}":`, e)
      }
    }
  }

  // 4. Process luminaQueryIndex / queryIndex in fallback stream
  const indexMatches = [
    ...contentOutsideThink.matchAll(
      /(?:<tool_call[^>]*name=["']?)?<?\b(?:luminaQueryIndex|queryIndex)["']?>\s*([\s\S]*?)<\/(?:luminaQueryIndex|queryIndex)>/gi
    )
  ]
  for (const match of indexMatches) {
    const body = match[1] || ''
    const params = extractParamsFromBody(body, match[0])
    try {
      const { luminaQueryIndexTool } = await import('../../tools/luminaQueryIndex')
      const res: any = await (luminaQueryIndexTool.execute as any)(params)
      const badgeBlock = `<lumina-index>\n${res.summaryMarkdown || res.summary || ''}\n</lumina-index>`
      fullContent = fullContent.replace(match[0], badgeBlock)
    } catch (err) {
      console.warn('[StreamRunner] Fallback index execution failed:', err)
    }
  }

  // 5. Process diagnoseSystem / luminaDiagnoseSystem in fallback stream
  const doctorMatches = [
    ...contentOutsideThink.matchAll(
      /(?:<tool_call[^>]*name=["']?)?<?\b(?:diagnoseSystem|luminaDiagnoseSystem)["']?>\s*([\s\S]*?)<\/(?:diagnoseSystem|luminaDiagnoseSystem)>/gi
    )
  ]
  for (const match of doctorMatches) {
    try {
      const { luminaDiagnoseSystemTool } = await import('../../tools/luminaDiagnoseSystem')
      const res: any = await (luminaDiagnoseSystemTool.execute as any)({})
      const badgeBlock = `<lumina-health>\n${res?.result ? JSON.stringify(res.result) : (res?.summary || '')}\n</lumina-health>`
      fullContent = fullContent.replace(match[0], badgeBlock)
    } catch (err) {
      console.warn('[StreamRunner] Fallback health execution failed:', err)
    }
  }

  // 6. Process auditWikilinks in fallback stream
  const auditMatches = [
    ...contentOutsideThink.matchAll(
      /(?:<tool_call[^>]*name=["']?)?<?\bauditWikilinks["']?>\s*([\s\S]*?)<\/auditWikilinks>/gi
    )
  ]
  for (const match of auditMatches) {
    try {
      const { auditWikilinksTool } = await import('../../tools/auditWikilinks')
      const res: any = await (auditWikilinksTool.execute as any)({})
      const badgeBlock = `<lumina-audit>\n${res?.result ? JSON.stringify(res.result) : (res?.summary || '')}\n</lumina-audit>`
      fullContent = fullContent.replace(match[0], badgeBlock)
    } catch (err) {
      console.warn('[StreamRunner] Fallback audit execution failed:', err)
    }
  }

  // Strip tool blocks from chat display if any were applied
  if (appliedCreations > 0 || appliedFolders > 0 || appliedUpdates > 0 || appliedDeletions > 0) {
    const prefixes = ['```lumina-create ', '```lumina-update ']
    let text = fullContent
    for (const prefix of prefixes) {
      const escaped = prefix.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
      text = text.replace(new RegExp(escaped + '[^\\n]*\\n[\\s\\S]*?\\n```', 'g'), '')
    }
    text = text.replace(/<create(?:File|_file)[\s\S]*?<\/create(?:File|_file)>/gi, '')
    // Remove both sides of XML-style fallback tool blocks
    text = text.replace(/<\/?create(?:Folder|_folder)[^>]*>/gi, '')
    text = text.replace(/```lumina-delete\s+[^\n]+```\n?/g, '')
    text = text.replace(/\n{4,}/g, '\n\n\n').trim()

    if (!text || text.length < 20) {
      const parts = []
      if (appliedCreations > 0) parts.push(`${appliedCreations} file(s) about your request`)
      if (appliedFolders > 0) parts.push(`${appliedFolders} ${appliedFolders === 1 ? 'folder' : 'folders'}`)
      if (appliedUpdates > 0) parts.push(`${appliedUpdates} file(s) updated`)
      if (appliedDeletions > 0) parts.push(`Deleted`)
      return `I've ${parts.join(' and ')}. You can find them in your workspace!`
    }
    return cleanRawToolLeaks(text)
  }

  return cleanRawToolLeaks(fullContent)
}
